[mesh]
path = "resources/rock.obj"
animated = false

[material]
kd = [0.5, 0.5, 1.0]
ks = [0.1, 1.0, 0.1]
shininess = 3.0
toonDiscretize = 4.0
toonSpecularThreshold = 0.49

[lights]
positions = [[1.0, 3.0, -2.0], [-1.0, 3.0, -2.0]]
colors = [[0.9, 0.9, 0.9], [0.7, 0.3, 0.3]]
direction = [[-0.7, -1.5, 1.0],  [0.7, -1.5, 1.0]]
is_spotlight = [false, false]
has_texture = [false, true]
texture_path = ["resources/smiley.png", "resources/smiley.png"]

[camera]
lookAt = [-0.215165, 0.305033, 0.645589]
rotations = [0.450295, 0.617848, 0.0]
dist = 2

[render_settings]
diffuse_model = "normal-mapping" 
specular_model = "none"   
shadows = false            
pcf = false 