[mesh]
path = "resources/dragon.obj"
animated = false 

[material]
ks = [1.0, 0.782, 0.344]
kd = [1.0, 1.0, 1.0]
shininess = 3.0
toonDiscretize = 4.0
toonSpecularThreshold = 0.49
roughness = 0.5
metallic = 1.0

[lights]
# Define multiple lights with their respective positions, colors, etc.
positions = [
    [1.0, 1.5, 0.0],
    [-3.0, 2.0, 1.0],  # Second light
    [0.0, 10.0, -5.0]  # Third light
]
colors = [
    [1.0, 1.0, 1.0],
    [0.6, 0.2, 0.2],  # Second light color
    [0.2, 0.8, 0.4]   # Third light color
]
is_spotlight = [false, true, false]  # Second light is a spotlight
direction = [
    [-1.0, 0.0, 0.0],
    [0.0, -1.0, 0.0],  # Direction for second light (spotlight)
    [1.0, 1.0, 1.0]    # Third light direction
]
has_texture = [false, true, false]
texture_path = [
    "resources/smiley.png",   # Texture for the second light
    "resources/spotlight_texture.png",  # Second light's texture
    ""  # No texture for the third light
]


[camera]
lookAt = [0.0, 0.0, -1.0]
rotations = [0.0, 0.0, 0.0]
dist = 2.0
fovy = 50.0

[render_settings]
diffuse_model = "pbr" # or "lambert" or "toon" or "x-toon" or "pbr"
specular_model = "none" # or "phong" or "blinn-phong" or "toon"
shadows = false # or true
pcf = false # or false